In [39]:
import pandas as pd

In [40]:
# Baca file CSV
df = pd.read_csv("data_news/news.csv")

# Ubah kolom 'tgl' ke datetime
df['tgl'] = pd.to_datetime(df['tgl'])
df = df.sort_values(by='tgl', ascending=True)
#df['tgl'] = df['tgl'].dt.tz_localize('Asia/Jakarta')

df['tgl_only'] = df['tgl'].dt.date
df['jam_only'] = df['tgl'].dt.time

In [41]:
df

,tgl,judul,rss,nama_sumber,link_sumber,query,link_berita,konten,ringkasan,tgl_only,jam_only
0,2008-05-26 07:00:00,Ciputra Development Anggarkan Capex Rp 1 Triliun,Google News,detikFinance,https://finance.detik.com,CTRS,https://news.google.com/rss/articles/CBMioAFBV...,NaN,NaN,2008-05-26,07:00:00
1,2008-12-18 08:00:00,Fajar Surya Wisesa Beli Mesin Baru US$ 85 Juta,Google News,detikFinance,https://finance.detik.com,FASW,https://news.google.com/rss/articles/CBMingFBV...,NaN,NaN,2008-12-18,08:00:00
2,2010-05-10 07:00:00,"Ciputra Anggarkan Capex Rp 1,5 Triliun untuk D...",Google News,Kompas.com,https://www.kompas.com,CTRS,https://news.google.com/rss/articles/CBMiwwFBV...,NaN,NaN,2010-05-10,07:00:00
3,2010-05-10 07:00:00,"Ciputra Anggarkan Capex Rp 1,5 Triliun untuk D...",Google News,Kompas.com,https://www.kompas.com,CTRS,https://news.google.com/rss/articles/CBMilwFBV...,NaN,NaN,2010-05-10,07:00:00
4,2011-05-02 07:00:00,Festival Anak Sholeh Walibarokah (FASW) 2011,Google News,LDII - Lembaga Dakwah Islam Indonesia,https://www.ldii.or.id,FASW,https://news.google.com/rss/articles/CBMidEFVX...,NaN,NaN,2011-05-02,07:00:00
...,...,...,...,...,...,...,...,...,...,...,...
16600,2025-11-05 02:02:00,Percepat Realisasi Manfaat Ekonomi Sektor Miga...,Google News,Sinar Jambi,https://sinarjambi.com,ekonomi,https://news.google.com/rss/articles/CBMizgFBV...,NaN,NaN,2025-11-05,02:02:00
16601,2025-11-05 02:03:00,Bogor Buka Pendaftaran Calendar of Event 2026:...,Google News,Pojok Bogor,https://bogor.pojoksatu.id,BUKA,https://news.google.com/rss/articles/CBMi5gFBV...,NaN,NaN,2025-11-05,02:03:00
16602,2025-11-05 02:03:00,"Roti Kinasih: Lebih dari Sekadar Roti, Simbol ...",Google News,Target Hukum,https://targethukum.com,ROTI,https://news.google.com/rss/articles/CBMiuAFBV...,NaN,NaN,2025-11-05,02:03:00
16603,2025-11-05 02:07:00,Tema Hari Kesehatan Nasional 2025: Generasi Se...,Google News,Radar Solo,https://radarsolo.jawapos.com,LINK,https://news.google.com/rss/articles/CBMi5AFBV...,NaN,NaN,2025-11-05,02:07:00
16604,2025-11-05 02:11:00,Rekomendasi Saham Hari Ini: ACES hingga EXCL,Google News,MetroTVNews.com,https://www.metrotvnews.com,EXCL,https://news.google.com/rss/articles/CBMijgFBV...,NaN,NaN,2025-11-05,02:11:00

In [42]:
print(df.dtypes)

tgl            datetime64[ns]
judul                  object
rss                    object
nama_sumber            object
link_sumber            object
query                  object
link_berita            object
konten                float64
ringkasan             float64
tgl_only               object
jam_only               object
dtype: object

In [43]:
nw = df[['tgl_only', 'jam_only','nama_sumber', 'judul']].copy()
nw

,tgl_only,jam_only,nama_sumber,judul
0,2008-05-26,07:00:00,detikFinance,Ciputra Development Anggarkan Capex Rp 1 Triliun
1,2008-12-18,08:00:00,detikFinance,Fajar Surya Wisesa Beli Mesin Baru US$ 85 Juta
2,2010-05-10,07:00:00,Kompas.com,"Ciputra Anggarkan Capex Rp 1,5 Triliun untuk D..."
3,2010-05-10,07:00:00,Kompas.com,"Ciputra Anggarkan Capex Rp 1,5 Triliun untuk D..."
4,2011-05-02,07:00:00,LDII - Lembaga Dakwah Islam Indonesia,Festival Anak Sholeh Walibarokah (FASW) 2011
...,...,...,...,...
16600,2025-11-05,02:02:00,Sinar Jambi,Percepat Realisasi Manfaat Ekonomi Sektor Miga...
16601,2025-11-05,02:03:00,Pojok Bogor,Bogor Buka Pendaftaran Calendar of Event 2026:...
16602,2025-11-05,02:03:00,Target Hukum,"Roti Kinasih: Lebih dari Sekadar Roti, Simbol ..."
16603,2025-11-05,02:07:00,Radar Solo,Tema Hari Kesehatan Nasional 2025: Generasi Se...
16604,2025-11-05,02:11:00,MetroTVNews.com,Rekomendasi Saham Hari Ini: ACES hingga EXCL

In [53]:
# Ambil tanggal unik
unique_dates = nw['tgl_only'].unique()
unique_dates_str = [str(t) for t in unique_dates]
print(len(unique_dates_str))
print(unique_dates_str[:100])

909
['2008-05-26', '2008-12-18', '2010-05-10', '2011-05-02', '2012-02-07', '2012-05-22', '2013-05-13', '2013-06-23', '2013-08-05', '2013-10-03', '2014-01-04', '2014-01-14', '2014-03-13', '2014-04-15', '2014-04-16', '2014-04-28', '2014-05-12', '2014-05-20', '2014-05-28', '2014-06-04', '2014-06-30', '2014-10-04', '2014-10-15', '2014-10-27', '2015-01-08', '2015-01-30', '2015-06-23', '2015-06-30', '2015-08-07', '2015-09-30', '2015-12-11', '2015-12-18', '2016-02-04', '2016-04-29', '2016-06-16', '2016-06-22', '2016-10-24', '2016-10-25', '2016-12-05', '2016-12-23', '2017-01-12', '2017-01-13', '2017-01-23', '2017-01-25', '2017-02-24', '2017-03-28', '2017-04-04', '2017-04-25', '2017-05-19', '2017-07-06', '2017-07-26', '2017-07-31', '2017-10-12', '2017-10-18', '2017-12-14', '2017-12-15', '2017-12-18', '2018-01-03', '2018-01-31', '2018-02-15', '2018-02-18', '2018-03-11', '2018-04-12', '2018-04-13', '2018-05-01', '2018-05-07', '2018-05-16', '2018-05-22', '2018-05-28', '2018-06-04', '2018-06-06', '2018-06-20', '2018-06-25', '2018-06-26', '2018-07-09', '2018-07-24', '2018-07-25', '2018-08-13', '2018-08-20', '2018-10-09', '2018-10-16', '2018-11-13', '2018-11-14', '2018-11-28', '2018-12-07', '2018-12-20', '2019-01-14', '2019-01-15', '2019-01-16', '2019-01-18', '2019-01-28', '2019-01-29', '2019-02-07', '2019-02-13', '2019-02-19', '2019-03-08', '2019-03-15', '2019-04-04', '2019-04-11', '2019-04-25']

In [49]:
nw

,tgl_only,jam_only,nama_sumber,judul
0,2008-05-26,07:00:00,detikFinance,Ciputra Development Anggarkan Capex Rp 1 Triliun
1,2008-12-18,08:00:00,detikFinance,Fajar Surya Wisesa Beli Mesin Baru US$ 85 Juta
2,2010-05-10,07:00:00,Kompas.com,"Ciputra Anggarkan Capex Rp 1,5 Triliun untuk D..."
3,2010-05-10,07:00:00,Kompas.com,"Ciputra Anggarkan Capex Rp 1,5 Triliun untuk D..."
4,2011-05-02,07:00:00,LDII - Lembaga Dakwah Islam Indonesia,Festival Anak Sholeh Walibarokah (FASW) 2011
...,...,...,...,...
16600,2025-11-05,02:02:00,Sinar Jambi,Percepat Realisasi Manfaat Ekonomi Sektor Miga...
16601,2025-11-05,02:03:00,Pojok Bogor,Bogor Buka Pendaftaran Calendar of Event 2026:...
16602,2025-11-05,02:03:00,Target Hukum,"Roti Kinasih: Lebih dari Sekadar Roti, Simbol ..."
16603,2025-11-05,02:07:00,Radar Solo,Tema Hari Kesehatan Nasional 2025: Generasi Se...
16604,2025-11-05,02:11:00,MetroTVNews.com,Rekomendasi Saham Hari Ini: ACES hingga EXCL

In [52]:
import yfinance as yf

# Simbol IHSG di Yahoo Finance
symbol = "^JKSE"

data = yf.download(symbol, start="2025-01-01", end="2025-11-05", interval='1d')
print(data.tail())

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['^JKSE']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

Empty DataFrame
Columns: [(Adj Close, ^JKSE), (Close, ^JKSE), (High, ^JKSE), (Low, ^JKSE), (Open, ^JKSE), (Volume, ^JKSE)]
Index: []